
version: "3"

services:
   backend:
      build: ./php
      depends_on:
         - mysql
      env_file:
         - ./docker-compose-lesson.env
      environment:
         - MYSQL_HOST=mysql
   frontend:
      build: ./frontend
      depends_on:
         - backend
      ports:
         - 80:80
   mysql:
      build: ./mysql
      env_file:
         - ./docker-compose-lesson.env
      ports:
         - 33006:3306